2014-02-05T22:20:59.403422+00:00 app[web.1]: 2014-02-05 22:20:59 [7] [INFO] Worker exiting (pid: 7)
2014-02-05T22:20:59.403214+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:20:59.402115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:20:59.402115+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:20:59.402115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:20:59.402115+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:20:59.402673+00:00 app[web.1]:     worker.init_process()
2014-02-05T22:20:59.402115+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:20:59.402673+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-05T22:20:59.402673+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-05T22:20:59.402673+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:20:59.402847+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:20:59.402847+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:20:59.402673+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-05T22:20:59.402673+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-05T22:20:59.402847+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:20:59.402847+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:20:59.402847+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-05T22:20:59.402847+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:20:59.403214+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:20:59.403214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:20:59.403214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:20:59.403214+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:20:59.403214+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:20:59.403422+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:20:59.403214+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:20:59.403214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:20:59.565688+00:00 app[web.1]: 2014-02-05 22:20:59 [2] [INFO] Shutting down: Master
2014-02-05T22:20:59.565688+00:00 app[web.1]: 2014-02-05 22:20:59 [2] [INFO] Reason: Worker failed to boot.
2014-02-05T22:21:01.901982+00:00 heroku[web.1]: Starting process with command `gunicorn eventex.wsgi`
2014-02-05T22:21:03.341111+00:00 app[web.1]: 2014-02-05 22:21:03 [2] [INFO] Starting gunicorn 18.0
2014-02-05T22:21:03.341751+00:00 app[web.1]: 2014-02-05 22:21:03 [2] [INFO] Listening at: http://0.0.0.0:58129 (2)
2014-02-05T22:21:03.341826+00:00 app[web.1]: 2014-02-05 22:21:03 [2] [INFO] Using worker: sync
2014-02-05T22:21:03.350675+00:00 app[web.1]: 2014-02-05 22:21:03 [7] [INFO] Booting worker with pid: 7
2014-02-05T22:21:03.446336+00:00 app[web.1]: 2014-02-05 22:21:03 [7] [ERROR] Exception in worker process:
2014-02-05T22:21:03.446336+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-05T22:21:03.446336+00:00 app[web.1]: Traceback (most recent call last):
2014-02-05T22:21:03.446336+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-05T22:21:03.446336+00:00 app[web.1]:     worker.init_process()
2014-02-05T22:21:03.446336+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-05T22:21:03.446336+00:00 app[web.1]:     self.callable = self.load()
2014-02-05T22:21:03.446336+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-05T22:21:03.446336+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-05T22:21:03.446592+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-05T22:21:03.446592+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-05T22:21:03.446592+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:21:03.446592+00:00 app[web.1]:     __import__(module)
2014-02-05T22:21:03.446592+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:21:03.446336+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-05T22:21:03.446592+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:21:03.446797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-05T22:21:03.446797+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:21:03.446592+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-05T22:21:03.446592+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 2, in <module>
2014-02-05T22:21:03.446592+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:21:03.446797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:21:03.446592+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:21:03.446797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:21:03.446797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:21:03.446797+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:21:03.447344+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-05T22:21:03.446797+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:21:03.447344+00:00 app[web.1]:     worker.init_process()
2014-02-05T22:21:03.446797+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:21:03.446797+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:21:03.447344+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-05T22:21:03.446797+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:21:03.447344+00:00 app[web.1]: Traceback (most recent call last):
2014-02-05T22:21:03.447344+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:21:03.447344+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-05T22:21:03.447344+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-05T22:21:03.447344+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-05T22:21:03.447344+00:00 app[web.1]:     self.callable = self.load()
2014-02-05T22:21:03.447344+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-05T22:21:03.447534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:21:03.447534+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-05T22:21:03.447534+00:00 app[web.1]:     __import__(module)
2014-02-05T22:21:03.447534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:21:03.447534+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 2, in <module>
2014-02-05T22:21:03.447534+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-05T22:21:03.447947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:21:03.447534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:21:03.447534+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:21:03.447947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-05T22:21:03.447947+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:21:03.447947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:21:03.447947+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:21:03.447947+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:21:03.447947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:21:03.448143+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:21:03.448143+00:00 app[web.1]: 2014-02-05 22:21:03 [7] [INFO] Worker exiting (pid: 7)
2014-02-05T22:21:03.447534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-05T22:21:03.447947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:21:03.447534+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:21:03.447947+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:21:03.447947+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:21:03.571597+00:00 app[web.1]: 2014-02-05 22:21:03 [2] [INFO] Shutting down: Master
2014-02-05T22:21:03.571807+00:00 app[web.1]: 2014-02-05 22:21:03 [2] [INFO] Reason: Worker failed to boot.
2014-02-05T22:21:01.197959+00:00 heroku[web.1]: Process exited with status 3
2014-02-05T22:21:05.310177+00:00 heroku[web.1]: Process exited with status 3
2014-02-05T22:21:05.320207+00:00 heroku[web.1]: State changed from starting to crashed
