2014-02-05T22:02:50.243397+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:02:50.243397+00:00 app[web.1]:     self.callable = self.load()
2014-02-05T22:02:50.243567+00:00 app[web.1]:     __import__(module)
2014-02-05T22:02:50.243567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-05T22:02:50.243567+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-05T22:02:50.243567+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 2, in <module>
2014-02-05T22:02:50.243567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:02:50.243567+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:02:50.243985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-05T22:02:50.243985+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:02:50.243567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:02:50.243985+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:02:50.243985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:02:50.243985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:02:50.243985+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:02:50.243985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:02:50.243985+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:02:50.243567+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:02:50.243567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:02:50.244202+00:00 app[web.1]: 2014-02-05 22:02:50 [7] [INFO] Worker exiting (pid: 7)
2014-02-05T22:02:50.243985+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:02:50.243985+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:02:50.244202+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:02:50.360887+00:00 app[web.1]: 2014-02-05 22:02:50 [2] [INFO] Shutting down: Master
2014-02-05T22:02:50.361008+00:00 app[web.1]: 2014-02-05 22:02:50 [2] [INFO] Reason: Worker failed to boot.
2014-02-05T22:02:51.438458+00:00 heroku[web.1]: Process exited with status 3
2014-02-05T22:02:51.447466+00:00 heroku[web.1]: Starting process with command `gunicorn eventex.wsgi`
2014-02-05T22:02:52.693555+00:00 app[web.1]: 2014-02-05 22:02:52 [2] [INFO] Starting gunicorn 18.0
2014-02-05T22:02:52.700035+00:00 app[web.1]: 2014-02-05 22:02:52 [2] [INFO] Using worker: sync
2014-02-05T22:02:52.699565+00:00 app[web.1]: 2014-02-05 22:02:52 [2] [INFO] Listening at: http://0.0.0.0:39389 (2)
2014-02-05T22:02:52.733388+00:00 app[web.1]: 2014-02-05 22:02:52 [7] [INFO] Booting worker with pid: 7
2014-02-05T22:02:52.827161+00:00 heroku[web.1]: State changed from starting to up
2014-02-05T22:02:52.993849+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:02:52.993849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:02:52.993849+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:02:52.994065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-05T22:02:52.994065+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:02:52.994065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:02:52.994065+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:02:52.994065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:02:52.994065+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:02:52.994653+00:00 app[web.1]:     worker.init_process()
2014-02-05T22:02:52.994653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-05T22:02:52.994653+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-05T22:02:52.994653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-05T22:02:52.994653+00:00 app[web.1]:     self.callable = self.load()
2014-02-05T22:02:52.994653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-05T22:02:52.993653+00:00 app[web.1]: Traceback (most recent call last):
2014-02-05T22:02:52.993653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-05T22:02:52.994653+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-05T22:02:52.994848+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:02:52.994848+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-05T22:02:52.994848+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-05T22:02:52.994848+00:00 app[web.1]:     __import__(module)
2014-02-05T22:02:52.994848+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 2, in <module>
2014-02-05T22:02:52.994848+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-05T22:02:52.994848+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:02:52.994848+00:00 app[web.1]:     from django.core.handlers.wsgi import WSGIHandler
2014-02-05T22:02:52.994848+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 11, in <module>
2014-02-05T22:02:52.994848+00:00 app[web.1]:     from django.core.handlers import base
2014-02-05T22:02:52.995280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 12, in <module>
2014-02-05T22:02:52.995280+00:00 app[web.1]:     from django.db import connections, transaction
2014-02-05T22:02:52.995769+00:00 app[web.1]: 2014-02-05 22:02:52 [7] [INFO] Worker exiting (pid: 7)
2014-02-05T22:02:52.993653+00:00 app[web.1]:     return self.load_wsgiapp()
2014-02-05T22:02:52.993849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load_wsgiapp
2014-02-05T22:02:52.993653+00:00 app[web.1]:     worker.init_process()
2014-02-05T22:02:52.993653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process
2014-02-05T22:02:52.993653+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-02-05T22:02:52.993653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi
2014-02-05T22:02:52.993653+00:00 app[web.1]:     self.callable = self.load()
2014-02-05T22:02:52.993849+00:00 app[web.1]:   File "/app/eventex/wsgi.py", line 2, in <module>
2014-02-05T22:02:52.993849+00:00 app[web.1]:     from django.core.wsgi import get_wsgi_application
2014-02-05T22:02:52.993849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app
2014-02-05T22:02:52.993849+00:00 app[web.1]:     __import__(module)
2014-02-05T22:02:52.993849+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 1, in <module>
2014-02-05T22:02:52.993849+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-02-05T22:02:52.994065+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:02:52.994065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:02:52.994065+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:02:52.994653+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:02:52.994065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:02:52.993653+00:00 app[web.1]: 2014-02-05 22:02:52 [7] [ERROR] Exception in worker process:
2014-02-05T22:02:52.994653+00:00 app[web.1]: Traceback (most recent call last):
2014-02-05T22:02:52.994653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker
2014-02-05T22:02:52.995280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
2014-02-05T22:02:52.995280+00:00 app[web.1]:     % (desc, ENVIRONMENT_VARIABLE))
2014-02-05T22:02:52.995280+00:00 app[web.1]:     if settings.DEBUG:
2014-02-05T22:02:52.995280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
2014-02-05T22:02:52.995280+00:00 app[web.1]:     self._setup(name)
2014-02-05T22:02:52.995280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/__init__.py", line 83, in <module>
2014-02-05T22:02:52.995280+00:00 app[web.1]:     signals.request_started.connect(reset_queries)
2014-02-05T22:02:52.995280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 88, in connect
2014-02-05T22:02:52.993653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 62, in load
2014-02-05T22:02:52.995456+00:00 app[web.1]: ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
2014-02-05T22:02:53.145506+00:00 app[web.1]: 2014-02-05 22:02:53 [2] [INFO] Shutting down: Master
2014-02-05T22:02:53.145506+00:00 app[web.1]: 2014-02-05 22:02:53 [2] [INFO] Reason: Worker failed to boot.
2014-02-05T22:02:54.536321+00:00 heroku[web.1]: State changed from up to crashed
2014-02-05T22:02:54.537149+00:00 heroku[web.1]: State changed from crashed to starting
2014-02-05T22:02:54.522588+00:00 heroku[web.1]: Process exited with status 3
2014-02-05T22:03:12.070722+00:00 heroku[web.1]: State changed from starting to crashed
2014-02-05T22:03:12.715164+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path=/ host=dyesten-wttd.herokuapp.com request_id=3336931c-a210-4571-be8e-9a401b6e1bd9 fwd="179.236.83.167" dyno= connect= service= status=503 bytes=
